---
- name: Converge
  hosts: all

  tasks:
    - name: "Include ansible-role-yadm"
      include_role:
        name: "ansible-role-yadm"

    - name: "Test yadm module"
      yadm:
        repo: "https://github.com/crgwilson/all-of-the-dots.git"
        dest: "/root"
