---
- name: Prepare
  hosts: all

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_distribution == "Debian"

    - name: Update yum cache
      yum:
        update_cache: true
      when: ansible_distribution == "CentOS"

    - name: "Install git"
      package:
        name: "git"
